--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0 (Debian 16.0-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: budget_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.budget_user (
    id integer NOT NULL,
    name text
);


ALTER TABLE public.budget_user OWNER TO postgres;

--
-- Name: budget_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.budget_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenditure; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expenditure (
    id integer NOT NULL,
    user_id integer NOT NULL,
    category_id integer,
    value numeric NOT NULL,
    description text NOT NULL,
    date_occurred timestamp without time zone NOT NULL,
    create_date timestamp without time zone DEFAULT now(),
    modified_date timestamp without time zone DEFAULT now()
);


ALTER TABLE public.expenditure OWNER TO postgres;

--
-- Name: expenditure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expenditure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenditure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: budget_user budget_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.budget_user
    ADD CONSTRAINT budget_user_pkey PRIMARY KEY (id);


--
-- Name: expenditure expenditure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expenditure
    ADD CONSTRAINT expenditure_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

