-- new schema

CREATE TABLE budget_user (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text
);


CREATE TABLE expenditure (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id int NOT NULL,
	category_id int,
	value decimal NOT NULL,
	description text NOT NULL,
	date_occurred timestamp NOT NULL,
	create_date timestamp default now(),
	modified_date timestamp default now()
);
